### ISSUE TITLE
reproduce whisper embeddings

### ISSUE THREAD

**Issue by zkokaja** [hassonlab/247-pickling#148]
currently noticing differences and unable to reproduce

**Comment by zkokaja** [comment]
Aditi seems to have replicated this, so maybe it's a Ken-specific issue

**Comment by leoniekerken** [comment]
differences between Aditi and Leo were due to 
1) different encoding scripts, leading to different encoding plots - this is resolved
2) different versions of transformers (v4.23.1 vs v4.25.1) - leading to different tokenization, which causes different predictions - here I need to update to current version of transformers as well and fix this

**Comment by zkokaja** [comment]
previous comment was for encoder embeddings. need to check decoder embeddings as well. both for v4.25.1.

**Comment by leoniekerken** [comment]
Resolved: The problem was because in v4.25.1 (but not v4.23.1), an <|endoftext|> token is appended at the end of each sequence (https://github.com/huggingface/transformers/pull/19921). Solved by setting add_special_tokens = False in tokenizer.encode.

Both top1_pred and decoder embeddings are the same now for v4.23.1 and v4.25.1 - we'll use v4.25.1 from now on.
